### ISSUE TITLE
Creating my First Branch After Installing netbox-Branching result in: AttributeError("'NoneType' object has no attribute '_base_manager'")

### ISSUE THREAD

**Issue by HMohammad2520** [netboxlabs/netbox-branching#177] opened 2024-11-18 06:59 UTC
### Plugin Version

0.5.2

### NetBox Version

4.1.6

### Python Version

3.12.3

### Steps to Reproduce

1. Updated All of plugins and netbox to latest versions; Plugins:
    - netbox-metatype-importer -- 0.5.0
    - netbox-secrets -- 2.1.0
    - netbox-qrcode -- 0.0.15
    - netbox-topology-views -- 4.1.0
    - netbox-reorder-rack `I disabled this plugin because its not compatible with netbox-4.1.x`
 2. Updated Netbox from 4.0.8 to 4.1.6
 3. Installed Netbox Branching 0.5.2
 4. Create a Branch

### Expected Behavior

A working branch should get created

### Observed Behavior

Branch is created but not working
Got this error: AttributeError("'NoneType' object has no attribute '_base_manager'")
a job is created with Error State
the branch does not work
all of the database is in Changes Ahead section of the branch

**Comment by HMohammad2520** [comment] 2024-11-26 19:23
I have Figured out what was the cause of the problem,
The History of the Old Version was the problem ( Maybe the plugins history )
I backed up the history and removed all of them and the problem resolved !
but further testing is required
i will close the issue after i tested every part of the Netbox

**Comment by HMohammad2520** [comment] 2024-11-26 19:24
https://github.com/netbox-community/netbox/issues/7149

**Comment by arthanson** [comment] 2024-12-03 23:05
Closing this as dupe of https://github.com/netbox-community/netbox/issues/7149

**Closed by arthanson** 2024-12-03 23:05 UTC
Labels: type: bug

**Comment by xocoru** [comment] 2024-12-04 12:59
I have the same issue. I just installed branches and am trying to create the first branch. 

AttributeError("'NoneType' object has no attribute '_base_manager'")

no other details was provided.

**Comment by xocoru** [comment] 2024-12-04 13:10
How to debug it?

**Comment by HMohammad2520** [comment] 2025-02-04 12:13
@xocoru 
the problem is the old history objects.
you can remove them with netboxshell or using the netbox housekeeping service [Doc](https://netboxlabs.com/docs/netbox/en/stable/administration/housekeeping/)

just remove history records before the plugin installation.
after i have done this, it resolved the problem.
