### ISSUE TITLE
Running script in a branch creates objects in main

### ISSUE THREAD

**Issue by llamafilm** [netboxlabs/netbox-branching#160] opened 2024-10-26 01:36 UTC
### Plugin Version

0.5.1

### NetBox Version

4.1.4

### Python Version

3.12.7

### Steps to Reproduce

1. Create this custom script
2. Create a new branch and activate it
3. Run this script

```py
from dcim.models import Site
from extras.scripts import Script

class BranchDebug(Script):
    class Meta:
        name = "branch debugging"

    def run(self, data, commit):
        dummies = Site.objects.filter(name__startswith='dummy').count()
        newsite = f'dummy{dummies+1}'
        site = Site(name=newsite, slug=newsite)
        site.full_clean()
        site.save()
        self.log_success("Created new site!", obj=site)
```

### Expected Behavior

A new site should be created in the branch

### Observed Behavior

A new site is created in the main branch.  So the new branch shows it as "changes behind".

![image](https://github.com/user-attachments/assets/42065b0b-ad29-4afb-924c-14f21935ce06)

**Comment by arthanson** [comment] 2024-12-05 21:16
Closing as dupe of #148

**Closed by arthanson** 2024-12-05 21:16 UTC
Labels: type: bug, status: duplicate, app: branching
