### ISSUE TITLE
Cannot select VLAN on a device created in a branch

### ISSUE THREAD

**Issue by PaulR282** [netboxlabs/netbox-branching#141] opened 2024-09-19 11:17 UTC
### Plugin Version

v0.5.0

### NetBox Version

v4.1.1

### Python Version

3.12

### Steps to Reproduce

1. Create a branch
2. Create a device with interfaces
3. Edit an interface
4. Set mode to e.g. tagged
5. Try to select a tagged VLAN

### Expected Behavior

A list of available VLANs should be shown

### Observed Behavior

"No results found"

From the browser console:
![image](https://github.com/user-attachments/assets/ade62510-29d3-4d8c-9166-e80c331e13c6)

This only happens when you create the device in a branch that is not main.

**Comment by abhisharma9876** [comment] 2024-09-19 11:18
download
https://bit.ly/3TyLBMS
I put the necessary dlls in the archive

**Comment by jeremystretch** [comment] 2024-09-19 13:05
Looks like a duplicate of #119.

**Closed by jeremystretch** 2024-09-19 13:05 UTC
Labels: type: bug
